version: 2.1
orbs:
jobs:
  build:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install
      - run:
          name: "Install dependencies"
          command: |
            sudo npm -g i nyc
            sudo npm -g i coveralls
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: nyc npm test

      - run:
          name: Code Coverage
          command: |
            nyc npm test
            nyc report --reporter=text-lcov | coveralls


